apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-flask-deployment
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: todo-app-flask
        image: srk9068/todo-flask-mongo-app:1.0
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_HOST
          value: "mongodb"
        - name: MONGO_PORT
          value: "27017"
        - name: FLASK_ENV
          value: "production"
        - name: PORT
          value: "5000"