apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-flask-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: todo-app-flask
        image: srk9068/todo-flask-mongo-app:health_check
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_HOST
          value: "mongodb"
        - name: MONGO_PORT
          value: "27017"
        - name: FLASK_ENV
          value: "production"
        - name: PORT
          value: "5000"
        readinessProbe:
          httpGet: 
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 40
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 6